### PR TITLE
fix board headshot aspect ratio

### PR DESCRIPTION
**Pull request by SantaClaraUniversityACM**

### CODE REVIEW

**Comment by SantaClaraUniversityACM** [comment]
replaced board headshots with correct file types and aspect ratio

**Review by calvinwlim — APPROVED** [review]
this was me

**Comment by calvinwlim** [comment]
this me, i did this

**Review by Whee-il — APPROVED** [review]

**Comment by Whee-il** [comment]
Need to deploy update still

**Pull request merged**
