### PR TITLE
Updated ACM-W Members

### PR DESCRIPTION
**Pull request by beahackman**
- went into ACM-W profile photo folder, deleted old ones, and put in the new photos into that folder
- in BoardList.vue I updated the import section to import the new photos
- in BoardList.vue I went to the ACMWBoard objects and deleted former memebrs, and added the new ones

### CODE REVIEW

**Comment by Whee-il** [comment]
image
I tried running it on my end and got build errors. Seems like the actual image files are .jpg files, not .jpeg

**Comment by Whee-il** [comment]
image
Hmm still something isn't working. 
I think it might be
image
image

**Comment by Whee-il** [comment]
Just out of curiosity, is the build working on your machine?

**Comment by beahackman** [comment]
No, sorry I just realized I was completely misspelling her name across the
document but after that, it should be working. I'm so sorry lol I'll send
over a new one in a second.

**Comment by Whee-il** [comment]
image
Can you try building and testing on your own and commit when it compiles?

**Comment by Whee-il** [comment]
I took a look at this again and I think I think this error is because you can't use .JPG, you have to use .jpg for your image formats. You can just rename the files, there is no actual conversion required.

**Comment by beahackman** [comment]
Okay perfect. As of right now, we just had three new members who joined our
board so I'm waiting on their bios/photos to come in (should hopefully be
by Wednesday latest??) so I'll try to fix it up when I get those from them.
Thanks,
Beatrice

**Comment by Whee-il** [comment]
Sounds good. Could I ask you to also crop the photos to all be square? It displays them in a weird way rn 
image

**Comment by beahackman** [comment]
Okay yeah, I can play around with that when I get them in. I think I was
mostly having troubles trying to run it so I couldn't double check it.

**Review by Whee-il — APPROVED** [review]

**Review by jordanmosakowski — APPROVED** [review]

**Pull request merged**
